version: '3.8'
services:
  dev-db:
    image: postgis/postgis:13-3.1
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - buss_stops
  test-db:
    image: postgis/postgis:13-3.1
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - buss_stops

networks:
  buss_stops:
